name: 发布影像
description: 发布新的照片和说明
title: "[发布影像] "
labels:
  - publish
  - photo
body:
  - type: input
    id: title
    attributes:
      label: 标题
      placeholder: 例如：傍晚窗台
    validations:
      required: true
  - type: input
    id: image
    attributes:
      label: 图片地址
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 说明
      placeholder: 想配在照片旁边的文字
    validations:
      required: true
